// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Test.Context;

namespace Test.Context
{
    public partial interface ItestContextProcedures
    {
        Task<List<GetScheduledCampaignMessageTextResult>> GetScheduledCampaignMessageTextAsync(DateTime? scheduleDate, TimeSpan? scheduleTime, string searchText, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
