// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Context
{
    public partial class Campaign
    {
        public Campaign()
        {
            Schedule = new HashSet<Schedule>();
        }

        public int Code { get; set; }
        public int? FkMessage { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual Message FkMessageNavigation { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}