// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Test.Context
{
    public partial class GetScheduledCampaignMessageTextResult
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public TimeSpan? Start_Time { get; set; }
        public int Number_Contacts { get; set; }
        public string Message_Text { get; set; }
    }
}
