// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Context
{
    public partial class Message
    {
        public Message()
        {
            Campaign = new HashSet<Campaign>();
            MessageContent = new HashSet<MessageContent>();
        }

        public int Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual ICollection<MessageContent> MessageContent { get; set; }
    }
}