// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Context
{
    public partial class MessageContent
    {
        public int Code { get; set; }
        public int FkMessage { get; set; }
        public string MessageText { get; set; }

        public virtual Message FkMessageNavigation { get; set; }
    }
}